# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('tagline', models.CharField(max_length=100, null=True)),
                ('buyable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('picture', models.ImageField(blank=True, default=b'default.png', upload_to=b'faces/')),
                ('banner', models.ImageField(blank=True, upload_to=b'faces/')),
                ('url', models.URLField(blank=True, verbose_name=b'Website')),
                ('company', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('background', models.ImageField(blank=True, upload_to=b'faces')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='userprofiles.UserProfile')),
                ('rank', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofiles.Rank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
