# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('worth', models.DecimalField(decimal_places=2, max_digits=100)),
                ('expires', models.DateField(null=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
